# Generated by Django 3.2 on 2021-04-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo_list',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='TITLE', max_length=200)),
                ('is_completed', models.BooleanField(db_column='IS_COMPLETED')),
                ('description', models.TextField(db_column='description', max_length=1000)),
                ('created_at', models.DateField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateField(auto_now=True, db_column='UPDATED_AT')),
            ],
            options={
                'db_table': 'todo_list',
                'managed': False,
            },
        ),
    ]
