# Generated by Django 3.2 on 2021-04-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contents', models.TextField(db_column='contents', max_length=500)),
                ('created_at', models.DateField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateField(auto_now=True, db_column='UPDATED_AT')),
            ],
        ),
    ]
